another updated PR-3
twindle-co/twindle pull request #215
Opened 2020-10-16 11:15 UTC by tr0mbl3y

2020-10-16 17:24 UTC, johnjacobkenny commented
@tr0mbl3y there is a conflict, could you please resolve and make the commit 🙂

2020-10-16 19:13 UTC, tr0mbl3y commented
done!

2020-10-16 19:30 UTC, proful commented
2 approval?

2020-10-17 05:28 UTC, johnjacobkenny commented
Conflict again, please get two reviews too

2020-10-17 07:15 UTC, pranavgoel29 commented on docs/TEAM.md
> +- [Pranav Goel](https://github.com/pranavgoel29), I'm from India, Have basic knowledge of HTML, CSS, C++ and C, I'm currently learning Javascript.
You have re-entered some name here, remove them first and also follow the table format.

2020-10-17 07:20 UTC, pranavgoel29 commented on docs/TEAM.md
> +- [tr0mbley](https://github.com/tr0mbl3y) :learning how things works! nothing to share much
you should write it as
| [tr0mbley](https://github.com/tr0mbl3y) | learning how things works! nothing to share much |

2020-10-17 07:51 UTC, pranavgoel29 commented
Please first sync your forked repository with the main repository too.

2020-10-17 10:16 UTC, UnevenCoder approved these changes
Looks fine & ready to merge

2020-10-17 12:06 UTC, michaelcosj reviewed
I think you should check lines 14, 18 and 21

2020-10-17 14:16 UTC, tusharkandpal commented
Yes, please recheck it :)

2020-10-17 15:43 UTC, thunder-coding requested changes
Table is not looking proper

2020-10-17 15:53 UTC, johnjacobkenny commented
Could someone review once more

2020-10-17 15:57 UTC, ad3rinto approved these changes
Looks okay now,

2020-10-17 15:59 UTC, johnjacobkenny commented
I see lots of removed lines! 🙄

2020-10-17 15:59 UTC, tr0mbl3y commented
oh no what is happening

2020-10-17 16:00 UTC, pranavgoel29 commented
> Could someone review once more

I think removed two people by mistake I'm helping him to get that solved.

2020-10-17 16:00 UTC, sarathkumar6 requested changes
Needs change. Please fix the lines removed.

2020-10-17 16:01 UTC, sarathkumar6 commented
@pranavgoel29  Thanks for assisting here.

2020-10-17 16:54 UTC, pranavgoel29 approved these changes
Good to go.

2020-10-17 17:04 UTC, Rakesh-4 commented
@tr0mbl3y can you please update sunny's small mistake here before this thing gets merged. There's a line gap between `India` and `and`. Please move that line to the previous line to retain the format.

Sunny was trying to rectify it but unfortunately, he couldn't. Thanks
![Screen Shot 2020-10-17 at 10 32 00 pm](https://user-images.githubusercontent.com/72874693/96348743-94bf4a00-10c8-11eb-81e8-9f9bb4869fd3.png)

2020-10-17 17:09 UTC, pranavgoel29 commented
> @tr0mbl3y can you please update sunny's small mistake here before this thing gets merged. There's a line gap between `India` and `and`. Please move that line to the previous line to retain the format.
> 
> Sunny was trying to rectify it but unfortunately, he couldn't. Thanks
> ![Screen Shot 2020-10-17 at 10 32 00 pm](https://user-images.githubusercontent.com/72874693/96348743-94bf4a00-10c8-11eb-81e8-9f9bb4869fd3.png)

Fixed that too
@johnjacobkenny can you merge it now.

2020-10-17 17:10 UTC, tr0mbl3y commented
yes! done thanks  pranavgoel29

2020-10-17 17:12 UTC, Rakesh-4 commented
> yes! done thanks pranavgoel29

Thanks man

2020-10-17 17:18 UTC, tusharkandpal approved these changes
Afterall its ready... Great work 👍👍

2020-10-17 17:21 UTC, EYRAM565 approved these changes

2020-10-17 17:27 UTC, merged

2020-10-17 17:27 UTC, johnjacobkenny commented
Merged! Thanks everyone for coordinating and completing 🥳

2020-10-17 17:36 UTC, tr0mbl3y commented
finally! the **mystery of merge conflict** finished
thanks guys!