3rd pr neaz
twindle-co/twindle pull request #326
Opened 2020-10-18 13:08 UTC by Neaz-Mahmood

2020-10-18 14:24 UTC, ad3rinto requested changes
You need to put the "|" at the end of your addition.

2020-10-19 07:32 UTC, Neaz-Mahmood commented
resolved conflict issues

2020-10-19 07:36 UTC, tolgaerdonmez commented on docs/TEAM.md
> +|[Neaz Mahmood](https://github.com/Neaz-Mahmood)|I am from Dhaka, Bangladesh. I am a second year Computer Science undergraduate. I know besic html, css, javascript. I am here to learn & contribute to
It would be nice to correct 'besic' to 'basic' :)

2020-10-19 07:36 UTC, tolgaerdonmez reviewed
Nice pr 👍

2020-10-19 08:05 UTC, EYRAM565 approved these changes

2020-10-19 10:57 UTC, UnevenCoder requested changes
Confluct again

2020-10-19 16:36 UTC, EYRAM565 approved these changes

2020-10-20 04:45 UTC, closed without merging