renamed folders in playground/cli
twindle-co/twindle pull request #428
Opened 2020-10-21 15:25 UTC by dpavankvarma

current folder names :

![image](https://user-images.githubusercontent.com/25107841/96741429-66e74780-13df-11eb-91b5-6e2f9c73009b.png)

new names: 

![image](https://user-images.githubusercontent.com/25107841/96741550-8bdbba80-13df-11eb-9c20-43214b06f9cb.png)

2020-10-21 16:20 UTC, PrasoonPratham approved these changes

2020-10-21 20:09 UTC, ad3rinto requested changes
Please add a readme.md file to let people know what the "acceptable" file naming convention is.

2020-10-22 08:40 UTC, dpavankvarma commented
> Please add a readme.md file to let people know what the "acceptable" file naming convention is.

Created a naming convention readme file and resolved the conflicts

2020-10-22 09:39 UTC, piratelicorne approved these changes
folder renamed Ok

2020-10-22 09:48 UTC, merged