Done My 4th PR
twindle-co/twindle pull request #465
Opened 2020-10-23 07:02 UTC by praveen2896

adding profile image in respective folder and changes done in team.md

2020-10-23 11:22 UTC, Akshay2996 requested changes
Please see your image. It's stretched due to which the column is also stretched.

2020-10-23 15:43 UTC, Akshay2996 approved these changes
@proful Review this & approve it👍

2020-10-24 02:42 UTC, proful commented
@Akshay2996 we need another approval

2020-10-24 05:37 UTC, arthurbuhl commented
### Adding profile image in respective folder

@praveen2896: Its seems you have uploaded a 1MB image to the folder. Can you resize the image to 100x100 or 200x200 resolution and upload it again.

### Changes done in team.md

Have you removed these changes? Can you add them again. Thanks!

2020-10-26 14:12 UTC, praveen2896 commented
@arthurbuhl @Akshay2996 Reduced image resolution , please help to review and approve

2020-10-26 15:20 UTC, johnjacobkenny commented on playground/cli/json-to-pdf-cli/script.js
> +    console.log("PDF Succesfully saved in " + process.cwd() + "\\output.pdf");
Using "\\" may not be the ideal way to code the path. I think you should take a look at how to ensure that `\` or `/` is picked correctly based on the OS. Look into the `path` module builtin to nodejs.

2020-10-26 15:20 UTC, johnjacobkenny commented on playground/cli/json-to-pdf-cli/script.js
> +    console.log("PDF Succesfully saved in " + process.cwd() + "\\output.pdf");
Oh its a comment. Lol never mind.

2020-10-26 15:21 UTC, johnjacobkenny approved these changes

2020-10-26 15:26 UTC, merged