Third PR Updated TEAM.md
twindle-co/twindle pull request #606
Opened 2020-11-04 17:36 UTC by farivasf11

## Description

## Attach Screenshot

> Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

2020-11-05 00:11 UTC, RafaelBatman55 requested changes

2020-11-05 00:11 UTC, RafaelBatman55 commented on docs/TEAM.md
> +>>>>>>> b619046436d5ba6b684256ffe061e1f4f24bde4e
![image](https://user-images.githubusercontent.com/46648727/98181521-42609480-1ee2-11eb-8c49-caba291431a4.png)

Something went wrong, please check again your PR.

2020-11-05 04:29 UTC, johnjacobkenny commented
Conflict symbols are still there

2020-11-05 16:29 UTC, farivasf11 reviewed
Ready

2020-11-07 11:45 UTC, RafaelBatman55 requested changes
Please, check again @farivasf11

2020-11-07 11:45 UTC, RafaelBatman55 commented on docs/TEAM.md
> +|                                                                                          | [Adewale Abiola](https://github.com/princehaybee)            | I am a Nigerian. I have basic knowledge of
You copied this block twice (check from line 45).

You can see many members twice in this table.

2020-11-07 11:45 UTC, RafaelBatman55 commented on docs/TEAM.md
> +|                                                                                          | [Alexis Rivas](https://github.com/farivasf11)                 | Hello I'm from Mexico, i just graduated fo
Try to add your profile picture (Check #492)

**Note:** Size must be 80px.

2020-11-13 09:50 UTC, closed without merging