Formatting handlebars partials
twindle-co/twindle pull request #868
Opened 2020-11-29 15:31 UTC by Mira-Alf

## Description
* One Common twitter template for both epub and pdf generation, similar structure in place for github and hackernews
* Using partials to evaluate the pdf/epub content - the page structures are different for pdf and epub - so needed different renderTemplate processes
* Needs some testing

# Things to do
* Testing framework
* Some twitter weird scenarios cropped up
* Maybe some formatting changes needed in the templates

## Attach Screenshot

> Note 2 code reviewer approval needed. Approach in twitter group & discord channel.

2020-11-29 17:41 UTC, PuruVJ commented
Seems good.

2020-11-29 17:43 UTC, PuruVJ requested changes

2020-11-29 17:43 UTC, PuruVJ commented on twindle-cli/src/renderer/templates/twitter/Toc.hbs
> +<<<<<<< Updated upstream:twindle-cli/src/renderer/epub/twitter/Toc.hbs
Wait what is this?

2020-11-29 17:44 UTC, PuruVJ commented on twindle-cli/src/renderer/templates/twitter/Toc.hbs
> +<<<<<<< Updated upstream:twindle-cli/src/renderer/epub/twitter/Toc.hbs
This is from a merge conflict. Please resolve this part

2020-11-30 05:14 UTC, Mira-Alf commented
Sorry @PuruVJ I missed that part

2020-11-30 05:51 UTC, merged