Second PR -  simrin_joshi.md
twindle-co/twindle pull request #886
Opened 2020-12-04 05:00 UTC by simrin051

I am a passionate professional focused on full stack web development.
I have 1 year of professional experience in Angular and i am rigorously looking for opportunities in Node , Express and Database to mold me to become rich experienced full stack development.

2020-12-04 05:02 UTC, proful commented
Pls review  @twindle-co/developer**

2020-12-04 05:29 UTC, Akshay2996 commented
@simrinjoshi the markdown file is empty. Please see it.

2020-12-04 05:36 UTC, PuruVJ commented
The markdown is empty, but I don't see any issue in it. She can add herself to team.md later

2020-12-06 14:49 UTC, RafaelBatman55 requested changes
Check these issues to avoid to break lines.

2020-12-06 14:49 UTC, RafaelBatman55 commented on docs/TEAM.md
> + width="80px">
Keep the <img> code in the same line.

![image](https://user-images.githubusercontent.com/46648727/101283375-a8c62480-37b8-11eb-9aa3-c6d2c40c416b.png)

2020-12-06 14:49 UTC, RafaelBatman55 commented on docs/TEAM.md
> +passionate professional focussed on full stack web development. I have 1 year of professional experience in Angular , HTML ,CSS ,JavaScipt, Java and i am rigorously looking for opportunities in Node
Remove this space between "I am a" and "passionate professional..."

![image](https://user-images.githubusercontent.com/46648727/101283395-d317e200-37b8-11eb-8be8-d10821a82dab.png)

These kind of space splits your text between two blocks.

2020-12-06 15:57 UTC, PuruVJ approved these changes

2020-12-06 16:43 UTC, closed without merging