Alignment in Team.md
twindle-co/twindle pull request #976
Opened 2020-12-20 19:34 UTC by simrin051

![Twindle_Team](https://user-images.githubusercontent.com/26873360/102722641-74aa4200-4328-11eb-90be-9de2013082a4.PNG)

Alignment in Intermediate Section.

2020-12-21 06:21 UTC, Akshay2996 approved these changes

2020-12-22 03:55 UTC, PuruVJ commented
Seems good. Can be merged

2020-12-22 10:43 UTC, proful commented
```
<<<<<<< HEAD:docs/TEAM.md

-------------------------------------------------------------------------------------------------- |
=======
>>>>>>> 8badb2e12be6f1783583955fefd55602a2c7d702:misc/docs/TEAM.md

```

is appearing due to wrong merge conflict resolution

2020-12-23 08:45 UTC, Akshay2996 requested changes

2020-12-23 08:45 UTC, Akshay2996 commented on misc/docs/TEAM.md
> +>>>>>>> 8badb2e12be6f1783583955fefd55602a2c7d702:misc/docs/TEAM.md
@simrin051 See this & resolve this

2021-01-14 08:13 UTC, closed without merging