twindle dark theme
twindle-co/twindle pull request #993
Opened 2020-12-30 00:50 UTC by frankiefab100

## Description
Twindle dark theme

2020-12-30 17:11 UTC, Akshay2996 commented
Hi @frankiefab100 Can we get a Screenshot of what it looks like & no need to write so much CSS in dark-theme.css

You only have to write the CSS variables that needs to be changed i.e **only :root should remain & delete everything else in the CSS** Everything will work fine. Try this yourself first.

2020-12-30 17:15 UTC, Akshay2996 requested changes

2020-12-30 17:15 UTC, Akshay2996 commented on misc/twindle-web/dark-theme.css
> +}
Please can you fix this. Create a CSS variable & assign this color value to it. There are same problem in the whole file

2020-12-30 17:15 UTC, Akshay2996 commented on misc/twindle-web/dark-theme.css
> +}
Here too.

2020-12-30 17:15 UTC, Akshay2996 commented on misc/twindle-web/dark-theme.css
> +
Here too. Please see where there is color define, we can use CSS variable instead to minimize rewriting the code

2021-01-01 14:04 UTC, frankiefab100 commented
Okay, I will resolve this. Please give me some time.

2021-01-09 17:08 UTC, frankiefab100 commented
## This is the screenshot

![Twindle_Create_books_out_of_your_tweets](https://user-images.githubusercontent.com/46662771/104103984-85096900-52a5-11eb-8bfc-472aeb83d6d0.png)
![Twindle_2](https://user-images.githubusercontent.com/46662771/104103969-73c05c80-52a5-11eb-9193-a98fee536399.png)

2021-01-14 08:13 UTC, merged